# Generated by Django 3.2.20 on 2023-08-31 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('github_link', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.CharField(max_length=200, null=True)),
                ('salary_per_hour', models.IntegerField(default=0)),
            ],
        ),
    ]
