# Generated by Django 3.2.20 on 2023-09-01 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='experience',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='userdata',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
