# Generated by Django 3.2.20 on 2023-09-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20230901_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
