# Generated by Django 3.2.20 on 2023-09-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_userdata_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='experience',
            field=models.IntegerField(default=2023),
        ),
    ]
