# Generated by Django 3.2.20 on 2023-09-02 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20230901_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.userdata'),
        ),
    ]
