# Generated by Django 3.2.20 on 2023-09-03 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20230902_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='experience',
            new_name='experience_years',
        ),
        migrations.AddField(
            model_name='userdata',
            name='background',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='website',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='UserExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, null=True)),
                ('my_expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.expertise')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.userdata')),
            ],
        ),
    ]
