# Generated by Django 3.2.20 on 2023-09-03 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20230903_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexpertise',
            old_name='user_to',
            new_name='userdata',
        ),
    ]
