# Generated by Django 3.2.20 on 2023-09-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_userdata_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='details',
            field=models.CharField(default='None', max_length=1500, null=True),
        ),
    ]
