# Generated by Django 3.2.20 on 2023-09-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_remove_userdata_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='details',
            field=models.CharField(default=None, max_length=1500, null=True),
        ),
    ]
