# Generated by Django 3.2.20 on 2023-09-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_userdata_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='city',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='phone',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
