# Generated by Django 3.2.20 on 2023-09-04 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20230904_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(default=None, max_length=300, null=True)),
                ('title', models.CharField(default=None, max_length=30, null=True)),
                ('link', models.CharField(default=None, max_length=300, null=True)),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.userdata')),
            ],
        ),
    ]
